name: HanbookReader
options:
  bundleIdPrefix: com.hanttn0972
packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: 0.9.19
targets:
  HanbookReader:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources:
      - path: Sources
    dependencies:
      - sdk: libsqlite3.tbd
      - package: ZIPFoundation
    info:
      path: Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIMainStoryboardFile: ""
